apiVersion: v1
kind: Service

metadata:
  name: {{ include "ecommerce-real.fullname" . }}-user
  labels:
    {{- include "ecommerce-real.labels" . | nindent 4 }}

spec:
  type: ClusterIP

  selector:
    app: user-service

  ports:
    - name: http
      port: 8080
      targetPort: 8080

