apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "ecommerce-real.fullname" . }}-user
  labels:
    {{- include "ecommerce-real.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.userService.replicaCount }}

  selector:
    matchLabels:
      app: user-service

  template:
    metadata:
      labels:
        app: user-service

    spec:
      serviceAccountName: ecommerce-user
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/agent-sockets
            type: Directory

      containers:
        - name: user-service
          image: "{{ .Values.userService.image.repository }}:{{ .Values.userService.image.tag }}"
          imagePullPolicy: {{ .Values.userService.image.pullPolicy | quote }}

          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/agent-sockets
              readOnly: true

          ports:
            - name: http
              containerPort: 8080

          env:
            - name: DB_HOST
              value: "postgres"

            - name: DB_PORT
              value: "5432"

            - name: DB_NAME
              value: "{{ .Values.userService.database.name }}"

            - name: DB_USERNAME
              value: "{{ .Values.postgres.username }}"

            - name: DB_PASSWORD
              value: "{{ .Values.postgres.password }}"